# Generated by Django 5.1.4 on 2025-01-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machines', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='machine',
            name='materials',
            field=models.JSONField(blank=True, help_text="Supported materials with attributes, e.g., {'Plastic A1': {'color': 'black'}, 'Plastic A2': {'color': 'white'}}", null=True),
        ),
    ]
